### ISSUE TITLE
Zigbee support

### ISSUE THREAD

**Issue by gizmodok** [caseda/org.eurotronic#36]
Hi,

I thinking of buying spirit thermostat but with zigbee protocol. I don’t have Any zwave devices om my homey and I don’t want any issues with range. Are you maybe considering of supporting zigbee protocol for spirit thermostats?

[Spirit zigbee](https://eurotronic.org/produkte/zigbee-heizkoerperthermostat/spirit-zigbee/) 

Thanks
Kamil

**Comment by caseda** [comment]
Well, let's just say, there is a reason why I put z-wave specifically in the name of the app store.

If (when) the zigbee core rewrite is done by Athom, I might think about it (if I have the time (probably needs to be reverse engineered a little) and money to buy at least one), for now it is an hard no, not by me.

**Comment by gizmodok** [comment]
Ok I understand thanks for responding !

**Comment by sraka1** [comment]
@caseda the zigbee code rewrite has long since been done, do you plan on adding zigbee?

Also, the changelog on https://homey.app/en-us/app/org.eurotronic/Eurotronic-Technology/ isn't in line with this repo. Is the plugin not open source anymore?

**Comment by caseda** [comment]
This repo isn't THE repo anymore and is already 3 years old and **way** behind the current app in the appstore.
The current app's code is indeed not online, and will never be, ever since the app became an app I started working together with Eurotronic themselves.
The ZigBee valves are just too hard for my current coding abilities to add in the current app and have all the features that it can/should have, so still a future thing.
