### ISSUE TITLE
Error after inclusion

### ISSUE THREAD

**Issue by SPAeotec** [caseda/org.eurotronic#48]
Hi, 

I get the following error message after including the spirit.  Unfortunately I could not find the error myself. Do you have an idea what the problem is here?

2020-08-28 07:49:46 [log] [ManagerDrivers] [spirit_zwave] [0] ZwaveDevice has been inited
2020-08-28 07:49:46 [log] [ManagerDrivers] [spirit_zwave] [0] Node: 12 | Manufacturer id: 328 | ProductType id: 3 | Product id: 1 | Firmware Version: 0.16 | Hardware Version: 49 | Firmware id: 769 | Firmware Version Target 1: 0.2 | Secure: ✓ | Battery: false
(node:10868) UnhandledPromiseRejectionWarning: Error: invalid_setting_type
   at Remote IPC Process

(node:10868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-08-28 07:50:17 [err] [ManagerDrivers] [spirit_zwave] [0] Could not get capability value for capabilityId: target_temperature [Error: timeout
   at Remote IPC Process
] {
  message: 'timeout'
}
2020-08-28 07:50:17 [err] [ManagerDrivers] [spirit_zwave] [0] Could not get capability value for capabilityId: eurotronic_manual_value [Error: timeout
   at Remote IPC Process
] {
  message: 'timeout'

Cheers
Sebastian

**Comment by caseda** [comment]
Hello @SPAeotec,
Glad you are showing interest in this repository, but this is currently not the official repository anymore and not up to date with all issues fixed that is currently in the appstore.

The errors currently showing in this repository are only a value _type_ error of synchronizing the "child lock" value to the settings (`.toString()` not working properly).
And timeout errors that can only be fixed in SDKv3 as those are core "issues" but these are only supervisial and won't be noticed by the end user.
There is another small "issue" in this code, also related to the child lock which is also not in this repository.

Judging your username and you trying this code instead of using the app that is currently in the app store, can I assume you work for Aeotec?
And want to add the rebranded Aeotec thermostat to the Aeotec app?
If so I don't mind working together to give you the updated code with everything fixed, but wouldn't like it if my code was just copy pasted without any consent.

**Comment by SPAeotec** [comment]
You have correctly recognized that we are currently looking for a way to better integrate our products into Homey. Therefore we look around and test different device drivers for their function and contact the respective developers. 

I already had the assumption that it can not be the current driver. I have seen that you have already included our thermostat in the Eurotronics app. For which we are grateful.

If you have a bugfixed version, we would be interested in testing it and if necessary include it in the Aeotec app.

**Comment by caseda** [comment]
sorry for the late responds, the master branch here should now have the latest device.js for the spirit (and your re-branded one as that is pretty much the same driver).

If you have any questions (not just for this driver) feel free to ask them.
